title: "CSS Battle #<number> – <Problem Name>"
labels: ["CSS Battles"]
body:
  - type: input
    id: link
    attributes:
      label: battle Link
      description: Link to battle
      placeholder: https//cssbatle.dev/play/number
      value: | 
       [Lets battle!](https://cssbatle.dev/play/number)
    validations:
      required: true