title: "CSS Battle #<number> – <Problem Name>"
labels: ["CSS Battles"]
body:
  - type: input
    id: link
    attributes:
      label: Link to battle
      description: Replace number with current battle number
      placeholder: https//cssbatle.dev/play/number
      value: | 
       [Lets battle!](https://cssbattle.dev/play/number)
    validations:
      required: true
  - type: textarea    
    attributes:
      label: "Let's see the solutions! - copy code and paste into your msg"
      description: Solution template for players
      placeholder: |
        ```html
        <details>
        <summary>Description – <strong>score {characters}</strong></summary><br />
        <!-- Has to be followed by an empty line! -->

        <!-- remove + character -->
        +```html
        Your CSSBattles.dev code here!
        +```

        </details>
        ```
      value: |
        ```html
        <details>
        <summary>Description – <strong>score {characters}</strong></summary><br />
        <!-- Has to be followed by an empty line! -->

        <!-- remove + character -->
        +```html
        Your CSSBattles.dev code here!
        +```

        </details>
        ```    
    validations:
      required: true                          
  - type: textarea    
    attributes:
      label: "What others will see"
      description: Showcase
      value: |        
        This will result in a nice hidden bit like so:<br />
        <details>
        <summary>Description – <strong>score {characters}</strong></summary><br />            
        Your CSSBattles.dev code here!        
        </details>        
    validations:
      required: true
 - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://virtualcoffee.io/code-of-conduct/)
      options:
        - label: I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community
          required: true
